#! /usr/bin/env ruby

require "rubygems"
require "bundler/setup"

require "newrelic_plugin"

module PtHeartbeatAgent

  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.scoutmob.pt_heartbeat"
    agent_version "1.0.1"
    agent_config_options :name, :server_id, :database
    agent_human_labels("pt-heartbeat") { "pt-heartbeat" }

    def poll_cycle
      lag = `sudo pt-heartbeat -D #{database} --check --master-server-id=#{server_id}`
      puts lag
      report_metric "ReplicationLag", "Value", lag.to_f
    end

  end

  #
  # Register this agent with the component.
  # The ExampleAgent is the name of the module that defines this
  # driver (the module must contain at least three classes - a
  # PollCycle, a Metric and an Agent class, as defined above).
  #
  NewRelic::Plugin::Setup.install_agent :pt_heartbeat, PtHeartbeatAgent

  #
  # Launch the agent; this never returns.
  #
  NewRelic::Plugin::Run.setup_and_run

end
