#! /usr/bin/env ruby

require "rubygems"
require "bundler/setup"

require "newrelic_plugin"

module PtHeartbeatAgent

  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.scoutmob.pt_heartbeat"
    agent_version "1.0.3"
    agent_config_options :name, :master_server_id, :database, :user, :password, :host
    agent_human_labels("pt-heartbeat") { "pt-heartbeat on #{name}" }

    def poll_cycle
      heartbeat_options = [
        '-D', database,
        '--utc',
        '--check'
      ]

      if master_server_id
        heartbeat_options << "--master-server-id=#{master_server_id}"
      end

      if user
        heartbeat_options << '-u'
        heartbeat_options << user
      end

      if password
        heartbeat_options << '-p'
        heartbeat_options << password
      end

      if host
        heartbeat_options << '-h'
        heartbeat_options << host
      end

      lag = `sudo pt-heartbeat #{heartbeat_options.join(' ')}`
      puts lag
      report_metric "ReplicationLag", "Value", lag.to_f
    end

  end

  #
  # Register this agent with the component.
  # The ExampleAgent is the name of the module that defines this
  # driver (the module must contain at least three classes - a
  # PollCycle, a Metric and an Agent class, as defined above).
  #
  NewRelic::Plugin::Setup.install_agent :pt_heartbeat, PtHeartbeatAgent

  #
  # Launch the agent; this never returns.
  #
  NewRelic::Plugin::Run.setup_and_run

end
